url: http://ojins.com
baseurl: /phb


# Site settings
title: 平衡宝
email: contact@ojins.com
description: "为您提供安全省心的股票自动优化方案"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Han Xiao
  pic: 1
  position: Designer
  social:
    - title: linkedin
      url: #

- name: Teng Qiu
  pic: 2
  position: Lead Marketer
  social:
    - title: linkedin
      url: #  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Berlin, Germany

# Build settings
markdown: kramdown
permalink: pretty
